In [1]:
import optuna
from pathlib import Path
import sqlite3
import pandas as pd

In [5]:
sqlite_file = Path("/Users/thomassimader/Documents/NIRB/db_1.0e-05min_max.sqlite3")

In [6]:
# Query to select all rows from the 'studies' table
# Connect to the SQLite database
conn = sqlite3.connect(sqlite_file)
cursor = conn.cursor()
cursor.execute("SELECT * FROM studies")
# Fetch all results
rows = cursor.fetchall()
# Get column names
column_names = [description[0] for description in cursor.description]
# Optionally, display as a DataFrame for better readability
df = pd.DataFrame(rows, columns=column_names)
print(df)

   study_id study_name
0         1    sweep_1

In [8]:
storage = f"sqlite:///{sqlite_file}"
loaded_study = optuna.load_study(study_name="sweep_1", storage= storage)

In [9]:
df = loaded_study.trials_dataframe()
df

,number,value,datetime_start,datetime_complete,duration,params_activation,params_batch_size,params_hidden_layers_betw0,params_hidden_layers_betw1,params_hidden_layers_betw2,params_hidden_layers_betw3,params_hidden_layers_betw4,params_hidden_layers_betw5,params_hiden1,params_hiden6,params_lr,params_num_inbetw_layers,state
0,0,None,2025-05-21 13:41:27.955120,2025-05-21 13:41:28.269296,0 days 00:00:00.314176,sigmoid,74,70,382.0,298.0,NaN,NaN,NaN,59,110,0.000194,3,FAIL
1,1,None,2025-05-21 13:41:27.958153,2025-05-21 13:41:28.493748,0 days 00:00:00.535595,tanh,83,56,264.0,NaN,NaN,NaN,NaN,48,168,0.000937,2,FAIL
2,2,None,2025-05-21 13:41:27.963363,2025-05-21 13:41:28.524093,0 days 00:00:00.560730,relu,85,286,238.0,238.0,258.0,82.0,NaN,29,28,0.000087,5,FAIL
3,3,None,2025-05-21 13:41:27.983041,2025-05-21 13:41:28.362790,0 days 00:00:00.379749,relu,93,354,NaN,NaN,NaN,NaN,NaN,97,162,0.000942,1,FAIL
4,4,None,2025-05-21 13:41:27.995412,2025-05-21 13:41:28.623946,0 days 00:00:00.628534,relu,99,68,234.0,54.0,222.0,116.0,234.0,82,180,0.000089,6,FAIL
5,5,None,2025-05-21 13:41:28.007551,2025-05-21 13:41:28.538034,0 days 00:00:00.530483,relu,83,236,300.0,152.0,228.0,150.0,NaN,34,58,0.000520,5,FAIL
6,6,None,2025-05-21 13:41:28.016188,2025-05-21 13:41:28.407957,0 days 00:00:00.391769,tanh,63,272,170.0,56.0,174.0,NaN,NaN,41,18,0.000288,4,FAIL
7,7,None,2025-05-21 13:41:28.031548,2025-05-21 13:41:28.252801,0 days 00:00:00.221253,relu,49,262,368.0,NaN,NaN,NaN,NaN,80,114,0.000658,2,FAIL
8,8,None,2025-05-21 13:41:28.045013,2025-05-21 13:41:28.477930,0 days 00:00:00.432917,leaky_relu,73,366,388.0,188.0,80.0,NaN,NaN,55,126,0.000408,4,FAIL
9,9,None,2025-05-21 13:41:28.055886,2025-05-21 13:41:28.468895,0 days 00:00:00.413009,leaky_relu,87,106,244.0,302.0,296.0,290.0,NaN,6,146,0.000484,5,FAIL
10,10,None,2025-05-21 13:58:37.905136,NaT,NaT,relu,24,182,180.0,98.0,110.0,140.0,352.0,88,98,0.000379,6,RUNNING
11,11,None,2025-05-21 13:58:38.286317,NaT,NaT,sigmoid,71,122,376.0,NaN,NaN,NaN,NaN,97,118,0.000049,2,RUNNING
12,12,None,2025-05-21 13:58:38.304288,NaT,NaT,relu,46,260,154.0,232.0,348.0,NaN,NaN,36,22,0.000336,4,RUNNING
13,13,None,2025-05-21 13:58:38.308723,NaT,NaT,leaky_relu,40,362,338.0,NaN,NaN,NaN,NaN,49,152,0.000028,2,RUNNING
14,14,None,2025-05-21 13:58:38.322218,NaT,NaT,tanh,42,290,236.0,NaN,NaN,NaN,NaN,89,122,0.000158,2,RUNNING
15,15,None,2025-05-21 13:58:38.335677,NaT,NaT,relu,74,82,328.0,112.0,174.0,NaN,NaN,33,154,0.000217,4,RUNNING
16,16,None,2025-05-21 13:58:38.346679,NaT,NaT,relu,50,280,274.0,NaN,NaN,NaN,NaN,20,120,0.000333,2,RUNNING
17,17,None,2025-05-21 13:58:38.354736,NaT,NaT,sigmoid,62,360,182.0,188.0,182.0,294.0,116.0,22,70,0.000118,6,RUNNING
18,18,None,2025-05-21 13:58:38.363909,NaT,NaT,leaky_relu,96,382,132.0,224.0,116.0,324.0,164.0,99,156,0.000017,6,RUNNING
19,19,None,2025-05-21 13:58:37.907660,NaT,NaT,relu,68,136,190.0,NaN,NaN,NaN,NaN,18,80,0.000044,2,RUNNING
20,20,None,2025-05-21 14:03:33.777799,NaT,NaT,leaky_relu,27,132,264.0,376.0,NaN,NaN,NaN,56,92,0.000556,3,RUNNING
21,21,None,2025-05-21 14:03:33.936414,NaT,NaT,relu,92,118,392.0,342.0,54.0,170.0,182.0,70,42,0.000127,6,RUNNING
22,22,None,2025-05-21 14:03:33.957183,NaT,NaT,relu,53,394,296.0,138.0,NaN,NaN,NaN,95,38,0.000220,3,RUNNING
23,23,None,2025-05-21 14:03:33.929070,NaT,NaT,tanh,24,364,NaN,NaN,NaN,NaN,NaN,18,32,0.000014,1,RUNNING
24,24,None,2025-05-21 14:03:33.985527,NaT,NaT,sigmoid,54,192,NaN,NaN,NaN,NaN,NaN,18,12,0.000080,1,RUNNING
25,25,None,2025-05-21 14:03:33.785189,NaT,NaT,tanh,90,148,NaN,NaN,NaN,NaN,NaN,87,88,0.000118,1,RUNNING
26,26,None,2025-05-21 14:08:47.462997,NaT,NaT,sigmoid,43,356,122.0,222.0,258.0,356.0,NaN,98,150,0.000093,5,RUNNING
27,27,None,2025-05-21 14:08:47.506358,NaT,NaT,relu,73,208,168.0,NaN,NaN,NaN,NaN,16,174,0.000968,2,RUNNING
28,28,None,2025-05-21 14:08:47.498596,NaT,NaT,relu,57,234,300.0,324.0,130.0,328.0,NaN,48,114,0.000011,5,RUNNING
29,29,None,2025-05-21 14:08:47.470840,NaT,NaT,leaky_relu,62,262,220.0,NaN,NaN,NaN,NaN,69,30,0.000013,2,RUNNING
30,30,None,2025-05-21 14:08:47.491662,NaT,NaT,relu,62,284,182.0,128.0,200.0,362.0,NaN,89,26,0.000191,5,RUNNING
31,31,None,2025-05-21 14:12:53.030093,NaT,NaT,leaky_relu,37,398,112.0,226.0,330.0,304.0,NaN,12,134,0.000164,5,RUNNING
32,32,None,2025-05-21 14:12:53.056382,NaT,NaT,sigmoid,80,264,228.0,NaN,NaN,NaN,NaN,87,70,0.000149,2,RUNNING
33,33,None,2025-05-21 14:12:53.058676,NaT,NaT,relu,74,236,378.0,78.0,NaN,NaN,NaN,34,156,0.000102,3,RUNNING
34,34,None,2025-05-21 14:24:31.840368,NaT,NaT,tanh,87,196,NaN,NaN,NaN,NaN,NaN,75,104,0.000157,1,RUNNING
35,35,None,2025-05-21 14:24:31.849831,NaT,NaT,tanh,44,130,82.0,228.0,254.0,322.0,366.0,45,64,0.000035,6,RUNNING
36,36,None,2025-05-21 14:24:31.871574,NaT,NaT,sigmoid,85,92,NaN,NaN,NaN,NaN,NaN,38,84,0.000213,1,RUNNING
37,37,None,2025-05-21 14:30:49.094355,NaT,NaT,relu,50,96,60.0,62.0,344.0,NaN,NaN,74,58,0.000014,4,RUNNING
38,38,None,2025-05-21 14:30:49.140334,NaT,NaT,relu,23,66,146.0,388.0,350.0,168.0,246.0,73,140,0.000031,6,RUNNING
39,39,None,2025-05-21 14:30:49.182509,NaT,NaT,sigmoid,75,146,346.0,NaN,NaN,NaN,NaN,33,18,0.000035,2,RUNNING
40,40,None,2025-05-21 14:30:49.370084,NaT,NaT,relu,83,332,344.0,356.0,NaN,NaN,NaN,6,170,0.000042,3,RUNNING
41,41,None,2025-05-21 14:30:49.422147,NaT,NaT,leaky_relu,56,130,NaN,NaN,NaN,NaN,NaN,30,144,0.000212,1,RUNNING
42,42,None,2025-05-21 14:34:22.537901,NaT,NaT,relu,92,112,280.0,254.0,346.0,NaN,NaN,95,112,0.000015,4,RUNNING
43,43,None,2025-05-21 14:34:22.582729,NaT,NaT,sigmoid,96,378,NaN,NaN,NaN,NaN,NaN,86,158,0.000779,1,RUNNING
44,44,None,2025-05-21 14:34:22.622911,NaT,NaT,sigmoid,56,394,374.0,248.0,132.0,NaN,NaN,70,102,0.000460,4,RUNNING
45,45,None,2025-05-21 14:34:22.811306,NaT,NaT,leaky_relu,26,322,284.0,300.0,254.0,114.0,372.0,37,86,0.000012,6,RUNNING
46,46,None,2025-05-21 14:37:01.132635,NaT,NaT,leaky_relu,83,152,NaN,NaN,NaN,NaN,NaN,68,68,0.000132,1,RUNNING
47,47,None,2025-05-21 14:37:01.197713,NaT,NaT,sigmoid,73,278,162.0,220.0,112.0,NaN,NaN,3,94,0.000031,4,RUNNING
48,48,None,2025-05-21 14:37:01.418770,NaT,NaT,leaky_relu,25,72,322.0,84.0,280.0,142.0,222.0,91,182,0.000109,6,RUNNING
49,49,None,2025-05-21 14:41:08.659113,NaT,NaT,sigmoid,75,296,280.0,144.0,NaN,NaN,NaN,3,190,0.000022,3,RUNNING
50,50,None,2025-05-21 14:41:08.716237,NaT,NaT,relu,55,268,226.0,NaN,NaN,NaN,NaN,68,170,0.000269,2,RUNNING
51,51,None,2025-05-21 14:41:08.917842,NaT,NaT,relu,70,242,NaN,NaN,NaN,NaN,NaN,46,128,0.000106,1,RUNNING
52,52,None,2025-05-21 14:45:22.613447,NaT,NaT,sigmoid,87,282,208.0,NaN,NaN,NaN,NaN,17,34,0.000392,2,RUNNING
53,53,None,2025-05-21 14:45:22.685158,NaT,NaT,sigmoid,61,368,NaN,NaN,NaN,NaN,NaN,94,148,0.000032,1,RUNNING
54,54,None,2025-05-21 14:45:22.934899,NaT,NaT,tanh,74,330,242.0,114.0,148.0,NaN,NaN,96,72,0.000079,4,RUNNING

In [ ]:
# Path to your .db file




# Query to list all table names
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

# Extract table names from tuples
table_names = [table[0] for table in tables]
table_names

['studies',
 'version_info',
 'study_directions',
 'study_user_attributes',
 'study_system_attributes',
 'trials',
 'trial_user_attributes',
 'trial_system_attributes',
 'trial_params',
 'trial_values',
 'trial_intermediate_values',
 'trial_heartbeats',
 'alembic_version']

In [11]:
sqlite_file = Path("/Users/thomassimader/Documents/NIRB/data/01/results.db")
conn = sqlite3.connect(sqlite_file)
query = "SELECT * FROM nirb_results"
df = pd.read_sql_query(query, conn)
# Print the DataFrame
print(df)
# Close connection
conn.close()

   id               norm  Q2_scaled  Q2_unscaled  R2_scaled  R2_unscaled  \
0   1          mean_init   0.003705    85.938634   0.000899         -1.0
1   3          mean_init   0.001111    25.768858   0.001772         -1.0
2   4          mean_init   0.001788    41.485412   0.003077         -1.0
3   5       min_max_init   0.000675    15.648869   0.000387         -1.0
4   6            min_max   0.001833    72.982674   0.000857         -1.0
5   8  min_max_init_grad   0.002755    63.230234   0.001010         -1.0

      Version  Entropy_MSE  Entropy_R2
0  version_17     0.011517    0.690202
1  version_18     0.003384    0.763121
2  version_19     0.004874    0.835812
3   version_2     0.001736    0.806695
4  version_45     0.006295    0.713825
5   version_2     0.004185    0.836541

In [12]:
df

,id,norm,Q2_scaled,Q2_unscaled,R2_scaled,R2_unscaled,Version,Entropy_MSE,Entropy_R2
0,1,mean_init,0.003705,85.938634,0.000899,-1.0,version_17,0.011517,0.690202
1,3,mean_init,0.001111,25.768858,0.001772,-1.0,version_18,0.003384,0.763121
2,4,mean_init,0.001788,41.485412,0.003077,-1.0,version_19,0.004874,0.835812
3,5,min_max_init,0.000675,15.648869,0.000387,-1.0,version_2,0.001736,0.806695
4,6,min_max,0.001833,72.982674,0.000857,-1.0,version_45,0.006295,0.713825
5,8,min_max_init_grad,0.002755,63.230234,0.001010,-1.0,version_2,0.004185,0.836541